[package]
name = "searchnos"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "indexer"
path = "src/indexer/main.rs"

[[bin]]
name = "searcher"
path = "src/searcher/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elasticsearch = "8.5.0-alpha.1"
env_logger = "0.10.0"
log = "0.4.0"
nostr-sdk = { git = "https://github.com/rust-nostr/nostr.git", branch = "master" }
tokio = { version = "1", features = ["full"] }
tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"]}
serde = "~1"
serde_json = "~1"
axum = { version = "0.6.7", features = ["ws", "headers"] }
futures = "0.3"
tower-http = { version = "*", features = ["add-extension"] }
chrono = "0.4.24"
anyhow = "1.0.70"
